volumes:
  db-data: {}
  dbc-logs: {}

networks:
  n1:
    external: false

services:
  db:
    image: ${EX04_POSTGRES_IMAGE}
    # Refer to https://docs.docker.com/guides/databases/
    # about the docker-entrypoint-initdb.d directory
    volumes:
      - ./scripts/init/postgres/create-dbs.sh:/docker-entrypoint-initdb.d/create-dbs.sh
      - db-data:${EX04_POSTGRES_DATA_MOUNT_POINT}
    environment:
      - POSTGRES_USER=${EX04_POSTGRES_USER}
      - POSTGRES_PASSWORD=${EX04_POSTGRES_PASS}
      - EX04_WM_DB_NAME
      - EX04_WM_DB_USER_NAME
      - EX04_WM_DB_USER_PASS
      - EX04_WM_ARCHIVE_DB_NAME
      - EX04_WM_ARCHIVE_DB_USER_NAME
      - EX04_WM_ARCHIVE_DB_USER_PASS
    networks:
      n1:
        aliases:
          - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  dbc:
    image: ${EX04_DBC_IMAGE}
    volumes:
      # Do not mount the logs folder when using the MFT OOTB image
      # - dbc-logs:${EX04_DBC_LOGS_MOUNT_POINT}
      - ./scripts/init/dbc/:${EX04_DBC_SCRIPTS_MOUNT_POINT}
    networks:
      - n1
    depends_on:
      db:
        condition: service_healthy
    environment:
      - EX04_DBC_WM_HOME
      - EX04_POSTGRES_USER
      - EX04_POSTGRES_PASS
      - EX04_WM_DB_NAME
      - EX04_WM_DB_USER_NAME
      - EX04_WM_DB_USER_PASS
      - EX04_WM_ARCHIVE_DB_NAME
      - EX04_WM_ARCHIVE_DB_USER_NAME
      - EX04_WM_ARCHIVE_DB_USER_PASS
    env_file:
      - dbc.env
    entrypoint: ${EX04_DBC_SCRIPTS_MOUNT_POINT}/entrypoint.sh

