volumes:
  db-data:
    name: ex04-db-data
  mft-root:
    name: ex04-mft-root

networks:
  n1:
    external: false

services:
  db:
    image: ${EX04_POSTGRES_IMAGE}
    # Refer to https://docs.docker.com/guides/databases/
    # about the docker-entrypoint-initdb.d directory
    container_name: ex04-db
    volumes:
      - ./scripts/init/postgres/create-dbs.sh:/docker-entrypoint-initdb.d/create-dbs.sh
      - db-data:${EX04_POSTGRES_DATA_MOUNT_POINT}
    environment:
      - POSTGRES_USER=${EX04_POSTGRES_USER}
      - POSTGRES_PASSWORD=${EX04_POSTGRES_PASS}
      - EX04_WM_DB_NAME
      - EX04_WM_DB_USER_NAME
      - EX04_WM_DB_USER_PASS
      - EX04_WM_ARCHIVE_DB_NAME
      - EX04_WM_ARCHIVE_DB_USER_NAME
      - EX04_WM_ARCHIVE_DB_USER_PASS
    networks:
      n1:
        aliases:
          - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  adminer:
    image: adminer
    container_name: ex04-adminer
    networks:
      - n1
    ports:
      - ${EX04_PORT_PREFIX}80:8080
    depends_on:
      db:
        condition: service_healthy

  mft:
    image: ${EX04_MFT_IMAGE}
    container_name: ex04-mft
    networks:
      - n1
    depends_on:
      db:
        condition: service_healthy
    environment:
      - EX04_WM_DB_NAME
      - EX04_WM_DB_USER_NAME
      - EX04_WM_DB_USER_PASS

      - EX04_WM_ARCHIVE_DB_NAME
      - EX04_WM_ARCHIVE_DB_USER_NAME
      - EX04_WM_ARCHIVE_DB_USER_PASS
    volumes:
      - ./config/mft/application.properties:/opt/softwareag/IntegrationServer/application.properties
      - mft-root:/opt/mft-root
    ports:
      - ${EX04_PORT_PREFIX}55:5555
